markdown: kramdown
permalink: /:title.html
auto: true
relative_permalinks: false
highlighter: rouge

safe: true
lsi: false
pygments: true

author: Ivan Ivanenko
email: ivan.ivanenko@gmail.com
site: pdfap.com

url: http://pdfap.com